DROP DATABASE IF EXISTS eventool;
DROP ROLE IF EXISTS eventool;

CREATE ROLE eventool WITH PASSWORD '1234';
ALTER ROLE eventool WITH LOGIN superuser;

CREATE DATABASE eventool
WITH OWNER = eventool
ENCODING = 'UTF8'
TABLESPACE = pg_default
CONNECTION LIMIT = -1;
