// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  domain

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( err ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* err ) UnmarshalJSON([]byte) error { return nil }
func ( err ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* err ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_err *err

func ( errMsg ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* errMsg ) UnmarshalJSON([]byte) error { return nil }
func ( errMsg ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* errMsg ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_errMsg *errMsg

func ( errObj ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* errObj ) UnmarshalJSON([]byte) error { return nil }
func ( errObj ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* errObj ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_errObj *errObj
