// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package autdelivery

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson4a0f95aaDecodeEventoolInternalPkgAuthorizationDeliveryRest(in *jlexer.Lexer, out *AuthResp) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "status":
			out.Status = string(in.String())
		case "ID":
			out.Id = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4a0f95aaEncodeEventoolInternalPkgAuthorizationDeliveryRest(out *jwriter.Writer, in AuthResp) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix[1:])
		out.String(string(in.Status))
	}
	if in.Id != "" {
		const prefix string = ",\"ID\":"
		out.RawString(prefix)
		out.String(string(in.Id))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AuthResp) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4a0f95aaEncodeEventoolInternalPkgAuthorizationDeliveryRest(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AuthResp) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4a0f95aaEncodeEventoolInternalPkgAuthorizationDeliveryRest(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AuthResp) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4a0f95aaDecodeEventoolInternalPkgAuthorizationDeliveryRest(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AuthResp) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4a0f95aaDecodeEventoolInternalPkgAuthorizationDeliveryRest(l, v)
}
